[package]
name = "rustpython-pylib"
version = "0.1.0"
authors = ["RustPython Team"]
edition = "2018"
include = ["Cargo.toml", "src/**/*.rs", "Lib/**"]

[features]
default = ["compiled-bytecode"]
compiled-bytecode = ["rustpython-derive", "rustpython-bytecode"]

[dependencies]
rustpython-derive = { version = "0.1.2", path = "../../derive", optional = true }
rustpython-bytecode = { version = "0.1.2", path = "../../bytecode", optional = true }
